### ISSUE TITLE
Can we  add telegram bot over here ?

### ISSUE THREAD

**Issue by theparadoxer02** [navjot12/Facebook-YoutubeDL#1]
Since telegram bot are on heavy use these days , it might be more fruitful . Also i would love to contribute over here!

**Comment by navjot12** [comment]
Hi!
This project repository is for a facebook messenger bot. I have actually made an equivalent bot for telegram already. You can find it over here: https://github.com/navjot12/Telegram-YoutubeDL
It's not deployed on any remote server though. So have to run it locally for it to work. Perhaps there can be an improvement for that.

**Comment by theparadoxer02** [comment]
What more else needed to make this project better like front end and any other feature , i want to a part of it !

**Comment by navjot12** [comment]
Feel free to fork and update it as per your liking. The Facebook send API provides a lot of message templates which have been used to improve the UX. I'm not sure if telepot provides the same. Feel free to give it a whirl.
